# Generated by Django 4.0.4 on 2022-05-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0002_image_post_date_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='posts/'),
        ),
    ]
