# Generated by Django 4.0.4 on 2022-05-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0003_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image_category',
        ),
        migrations.RemoveField(
            model_name='location',
            name='image_location',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_category',
        ),
        migrations.AddField(
            model_name='image',
            name='image_category',
            field=models.ManyToManyField(to='Media.category'),
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_location',
        ),
        migrations.AddField(
            model_name='image',
            name='image_location',
            field=models.ManyToManyField(to='Media.location'),
        ),
    ]
