# Generated by Django 4.0.4 on 2022-05-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0005_alter_category_category_remove_image_image_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/images'),
        ),
    ]
