# Generated by Django 4.0.4 on 2022-05-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0006_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='', upload_to='static/images'),
        ),
    ]
